"""fix typo in permission_id column in roles_permissions table

Revision ID: 1d52180e5d05
Revises: 045c7407c1e5
Create Date: 2026-08-07 17:37:33.174543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d52180e5d05'
down_revision: Union[str, Sequence[str], None] = '045c7407c1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_permissions', sa.Column('permission_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('roles_permissions_Permission_id_fkey'), 'roles_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'roles_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_column('roles_permissions', 'Permission_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_permissions', sa.Column('Permission_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('roles_permissions_Permission_id_fkey'), 'roles_permissions', 'permissions', ['Permission_id'], ['id'])
    op.drop_column('roles_permissions', 'permission_id')
    # ### end Alembic commands ###
