"""add device_id column to attendance_record table

Revision ID: 36fd51bf5044
Revises: 033a11f77e06
Create Date: 2026-09-03 10:35:29.620263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fd51bf5044'
down_revision: Union[str, Sequence[str], None] = '033a11f77e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_record', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attendance_record', 'device', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_record', type_='foreignkey')
    op.drop_column('attendance_record', 'device_id')
    # ### end Alembic commands ###
