"""add is_active field to employee table

Revision ID: 396c69607ac1
Revises: f651226f643e
Create Date: 2026-08-31 13:15:15.515219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396c69607ac1'
down_revision: Union[str, Sequence[str], None] = 'f651226f643e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_active', sa.Boolean(), default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'is_active')
    # ### end Alembic commands ###
