"""set activation fiels to nullable

Revision ID: 549f3605cc89
Revises: c03aa1034a01
Create Date: 2026-08-12 12:11:12.971582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '549f3605cc89'
down_revision: Union[str, Sequence[str], None] = 'c03aa1034a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'activation_code_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('device', 'activation_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'activation_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('device', 'activation_code_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
