"""add cascade to foreign keys in role_permission table

Revision ID: 6217103eadb4
Revises: 03729e3f5fed
Create Date: 2026-08-11 13:18:10.169538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6217103eadb4'
down_revision: Union[str, Sequence[str], None] = '03729e3f5fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('role_permission_permission_id_fkey'), 'role_permission', type_='foreignkey')
    op.drop_constraint(op.f('role_permission_role_id_fkey'), 'role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'role', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permission', 'permission', ['permission_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.create_foreign_key(op.f('role_permission_role_id_fkey'), 'role_permission', 'role', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_permission_permission_id_fkey'), 'role_permission', 'permission', ['permission_id'], ['id'])
    # ### end Alembic commands ###
