"""add refresh_token_hash field to user table for token rotation

Revision ID: 9449e44f149d
Revises: c007e8325093
Create Date: 2026-08-15 22:33:22.653903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9449e44f149d'
down_revision: Union[str, Sequence[str], None] = 'c007e8325093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['refresh_token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'refresh_token_hash')
    # ### end Alembic commands ###
