"""add refresh_token_hash field to device table for token rotation

Revision ID: 9637d2d3b53a
Revises: 9449e44f149d
Create Date: 2026-08-15 23:20:07.107845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9637d2d3b53a'
down_revision: Union[str, Sequence[str], None] = '9449e44f149d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('refresh_token_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'device', ['refresh_token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='unique')
    op.drop_column('device', 'refresh_token_hash')
    # ### end Alembic commands ###
