"""rename activation_code_hash to activation_code in table device

Revision ID: c007e8325093
Revises: c14232a57db8
Create Date: 2026-08-15 17:19:35.183194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c007e8325093'
down_revision: Union[str, Sequence[str], None] = 'c14232a57db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('activation_code', sa.String(), nullable=True))
    op.drop_constraint(op.f('device_activation_code_hash_key'), 'device', type_='unique')
    op.create_unique_constraint(None, 'device', ['activation_code'])
    op.drop_column('device', 'activation_code_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('activation_code_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device', type_='unique')
    op.create_unique_constraint(op.f('device_activation_code_hash_key'), 'device', ['activation_code_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('device', 'activation_code')
    # ### end Alembic commands ###
