"""set device_id to not null in attendance_record table

Revision ID: d7b68c557337
Revises: 36fd51bf5044
Create Date: 2026-09-03 10:39:05.686420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b68c557337'
down_revision: Union[str, Sequence[str], None] = '36fd51bf5044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_record', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_record', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
