"""remove unique constraint on employee_id column of face_embedding table

Revision ID: f651226f643e
Revises: a49f56292f5a
Create Date: 2026-08-29 13:00:14.387098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f651226f643e'
down_revision: Union[str, Sequence[str], None] = 'a49f56292f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('face_embedding_employee_id_key'), 'face_embedding', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('face_embedding_employee_id_key'), 'face_embedding', ['employee_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
